spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 693023855454-gtv0uqibbbthbbtm86o5f4kej34efht0.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
  jpa:
    hiberante:
      ddl-auto: create
      format_sql: 'true'
    show-sql: 'true'
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:yonggamsa
    username: sa
    password:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat

